title: cybermugen.dev
author: Mugen T. 
url: https://www.abhinavsaxena.com/moonwalk # root address of the site
description: > # description of the site (multiple lines allowed)
  I like cybersecurity and stuff. Wannabe hacker. IT professional that still has a soul. Stick around. Or not! If you wanna chat, contact me here: sawyourwebsite@cybermugen.dev
permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "Take me back home!" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_diary: true # show diary entries added in _diary
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Fun stuff I made!
    title_misc_list: Details
    title_blog: Blog posts!
  # options for the "diary" page
  diary:
    diary_title: Daily-ish thoughts about life
    diary_description: Some thoughts about life to make me seem more human, because life is more than just tech and work. I'm not a robot, I swear!
  # options for the "blog" page
  blog:
    blog_title: Look! Stuff I wrote!
    blog_description:  Blog posts about various tech and security topics. This is a central spot for them, but they can also be found on LinkedIn, HashNode, and Medium. I do my best to post weekly!

collections:
  diary:
    output: true
  projects:
    output: true

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
